# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.1 "
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "ckb-contracts"
template_type = "Rust"
