# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.4.1"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "eth-bridge-typescript"
template_type = "Rust"

[[contracts]]
name = "eth-light-client-typescript"
template_type = "Rust"

[[contracts]]
name = "eth-bridge-lockscript"
template_type = "Rust"
